# Generated by Django 4.2.13 on 2026-07-22 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento porcentual aplicado en caja (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_sin_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del pedido antes de aplicar el descuento de caja.', max_digits=14, null=True),
        ),
    ]
