# Generated by Django 4.2.13 on 2026-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_pago_descuento_porcentaje_pago_monto_sin_descuento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('cajero',), name='unique_sesion_abierta_por_cajero'),
        ),
    ]
