# Generated by Django 4.2.13 on 2026-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_sesioncaja_unique_sesion_abierta_por_cajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente_razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente_ruc',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='condicion_venta',
            field=models.CharField(blank=True, default='Contado', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_comprobante',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('factura', 'Factura')], default='ticket', max_length=10),
        ),
    ]
