# Generated by Django 4.2.13 on 2026-09-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_pago_cliente_direccion_pago_cliente_razon_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.PositiveSmallIntegerField(help_text='Código E621: 1 Visa, 2 Mastercard, 3 Amex, 4 Maestro, 5 Panal, 6 Cabal, 99 Otra.')),
                ('denominacion_descripcion', models.CharField(blank=True, help_text='Solo para denominación 99: el nombre real de la tarjeta.', max_length=20)),
                ('forma_procesamiento', models.PositiveSmallIntegerField(default=1, help_text='Código E626: 1 POS, 2 pago electrónico, 9 otro.')),
                ('codigo_autorizacion', models.CharField(blank=True, help_text='El que imprime el voucher de la terminal.', max_length=10)),
                ('titular', models.CharField(blank=True, max_length=30)),
                ('ultimos_digitos', models.CharField(blank=True, help_text='Los últimos cuatro de la tarjeta. Nunca el número entero: guardarlo completo sería un problema de seguridad y el SIFEN tampoco lo pide.', max_length=4)),
                ('procesadora_ruc', models.CharField(blank=True, max_length=20)),
                ('procesadora_razon_social', models.CharField(blank=True, max_length=60)),
                ('numero_boleta', models.CharField(blank=True, help_text='Número del voucher, para cruzar con el resumen de la procesadora al cierre.', max_length=30)),
                ('origen', models.CharField(default='manual', help_text='Qué terminal produjo estos datos (manual, simulada, o el driver de la procesadora).', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_tarjeta', to='caja.pago')),
            ],
            options={
                'verbose_name': 'Datos de tarjeta',
                'verbose_name_plural': 'Datos de tarjeta',
                'db_table': 'caja_datos_tarjeta',
            },
        ),
    ]
