# Generated by Django 4.2.13 on 2026-09-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_datostarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.CreateModel(
            name='DatosCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Campo E631: ocho dígitos, completados con ceros a la izquierda. Se normaliza al guardar.', max_length=8)),
                ('banco', models.CharField(help_text='Campo E632: banco emisor, de 4 a 20 caracteres. El mínimo es del SIFEN, así que va el nombre y no la sigla.', max_length=20)),
                ('titular', models.CharField(blank=True, help_text='A nombre de quién está librado el cheque.', max_length=60)),
                ('fecha_cobro', models.DateField(blank=True, help_text='Fecha a partir de la cual el cheque se puede cobrar. Vacío = a la vista. Cargada = cheque diferido, que no es plata en el cajón todavía.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_cheque', to='caja.pago')),
            ],
            options={
                'verbose_name': 'Datos de cheque',
                'verbose_name_plural': 'Datos de cheque',
                'db_table': 'caja_datos_cheque',
            },
        ),
    ]
