# Generated by Django 4.2.13 on 2026-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_alter_pago_medio_pago_datoscheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=80),
        ),
    ]
