# Generated by Django 4.2.13 on 2026-09-24 14:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0007_merge_identidad_sync_codigo_barras'),
        ('ventas', '0003_identidad_sync'),
        ('caja', '0008_pago_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('motivo', models.CharField(choices=[('cambio', 'Cambio de producto'), ('estado_inadecuado', 'Devolución por estado inadecuado'), ('otro', 'Otro motivo')], max_length=20)),
                ('motivo_detalle', models.CharField(blank=True, help_text='Obligatorio con "Otro motivo"; opcional en el resto.', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('total_credito', models.DecimalField(decimal_places=2, help_text='Lo que vale, a precio cobrado, la mercadería que volvió.', max_digits=14)),
                ('monto_reintegro', models.DecimalField(decimal_places=2, default=0, help_text='Lo que salió de la caja hacia el cliente.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('medio_reintegro', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pago_cambio', models.OneToOneField(blank=True, help_text='El cobro del pedido de cambio, ya neto del crédito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_aplicada', to='caja.pago')),
                ('pago_original', models.ForeignKey(help_text='El cobro de la venta de la que vuelve la mercadería.', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='caja.pago')),
                ('pedido_cambio', models.OneToOneField(blank=True, help_text='Lo que el cliente se lleva a cambio, si se lleva algo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_de_cambio', to='ventas.notapedido')),
                ('sesion_caja', models.ForeignKey(help_text='El turno por el que se movió la plata, no el de la venta.', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='caja.sesioncaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'caja_devoluciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Crédito por esta línea, a precio cobrado.', max_digits=14)),
                ('reingresa_stock', models.BooleanField(default=True, help_text='False para mercadería dañada: vuelve al local pero no al stock vendible, o el showroom ofrecería piezas rotas.')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='caja.devolucion')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.itempedido')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_devueltos', to='productos.variante')),
            ],
            options={
                'verbose_name': 'Ítem devuelto',
                'verbose_name_plural': 'Ítems devueltos',
                'db_table': 'caja_items_devolucion',
            },
        ),
    ]
