# Generated by Django 4.2.13 on 2026-05-26 21:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo para cobrar'), ('pagado', 'Pagado — cerrado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('cliente_nombre', models.CharField(blank=True, max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, max_length=30)),
                ('cliente_observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones_deposito', models.TextField(blank=True)),
                ('fecha_preparacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('preparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_preparados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de pedido',
                'verbose_name_plural': 'Notas de pedido',
                'db_table': 'notas_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('preparado', models.BooleanField(default=False)),
                ('cantidad_preparada', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.notapedido')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='productos.variante')),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
                'db_table': 'items_pedido',
            },
        ),
        migrations.AddIndex(
            model_name='notapedido',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='idx_pedido_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='notapedido',
            index=models.Index(fields=['vendedor', 'estado'], name='idx_pedido_vendedor'),
        ),
    ]
