# Generated by Django 4.2.13 on 2026-06-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapedido',
            name='cliente_ruc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='notapedido',
            name='total_ajustado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto final negociado; reemplaza al total calculado si está definido', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Nombre o razón social', max_length=180)),
                ('ruc', models.CharField(blank=True, db_index=True, help_text='RUC o CI. Ej: 80012345-6', max_length=30)),
                ('tipo', models.CharField(choices=[('fisica', 'Persona física'), ('juridica', 'Persona jurídica / Empresa')], default='fisica', max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('condicion_venta', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', help_text='Condición de venta habitual de este cliente', max_length=12)),
                ('permite_ajuste_precio', models.BooleanField(default=False, help_text='Si es mayorista/constructora con precios negociables')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['ruc'], name='idx_cliente_ruc'), models.Index(fields=['razon_social'], name='idx_cliente_razon')],
            },
        ),
        migrations.AddField(
            model_name='notapedido',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente del padrón (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='ventas.cliente'),
        ),
    ]
