# Generated by Django 4.2.13 on 2026-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('encargada_ventas', 'Encargada de Ventas'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero'), ('deposito', 'Depósito')], default='vendedor', max_length=20),
        ),
    ]
