# Generated by Django 4.2.13 on 2026-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=80)),
                ('uid', models.UUIDField(db_index=True)),
                ('operacion', models.CharField(max_length=10)),
                ('motivo', models.CharField(choices=[('mas_nuevo', 'La fila local era más nueva'), ('no_existe', 'La fila referenciada no existe acá'), ('error', 'Error al aplicar')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('datos_recibidos', models.JSONField(blank=True, default=dict)),
                ('datos_locales', models.JSONField(blank=True, default=dict)),
                ('nodo_origen', models.CharField(max_length=60)),
                ('momento_recibido', models.DateTimeField(blank=True, null=True)),
                ('momento_local', models.DateTimeField(blank=True, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revisado', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'sync_conflictos',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodo', models.CharField(max_length=60, unique=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_exito', models.DateTimeField(blank=True, null=True)),
                ('cambios_enviados', models.PositiveIntegerField(default=0)),
                ('cambios_recibidos', models.PositiveIntegerField(default=0)),
                ('conflictos', models.PositiveIntegerField(default=0)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sync_estado',
            },
        ),
        migrations.CreateModel(
            name='CambioSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=80)),
                ('uid', models.UUIDField(db_index=True)),
                ('operacion', models.CharField(choices=[('alta', 'Alta'), ('cambio', 'Modificación'), ('baja', 'Baja')], max_length=10)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('nodo', models.CharField(db_index=True, max_length=60)),
                ('momento', models.DateTimeField(db_index=True)),
                ('empujado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'sync_cambios',
                'ordering': ['momento', 'id'],
                'indexes': [models.Index(fields=['empujado_en', 'momento'], name='sync_cambio_empujad_a5c9eb_idx'), models.Index(fields=['modelo', 'uid'], name='sync_cambio_modelo_e5a582_idx')],
            },
        ),
    ]
