# Generated by Django 4.2.13 on 2026-05-26 21:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('proveedor', 'Pago a proveedor'), ('salario', 'Salario de empleado'), ('servicio', 'Servicio / Utility'), ('otro', 'Otro gasto')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'db_table': 'categorias_gasto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, help_text='Salario mensual base en Gs.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='costos.categoriagasto')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_salario', to='costos.empleado')),
            ],
            options={
                'verbose_name': 'Gasto operativo',
                'verbose_name_plural': 'Gastos operativos',
                'db_table': 'gastos_operativos',
                'ordering': ['-anio', '-mes', '-fecha_creacion'],
            },
        ),
    ]
