# Generated by Django 4.2.13 on 2026-05-26 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastooperativo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gastooperativo',
            index=models.Index(fields=['anio', 'mes'], name='idx_gasto_periodo'),
        ),
        migrations.AddIndex(
            model_name='gastooperativo',
            index=models.Index(fields=['estado', 'anio', 'mes'], name='idx_gasto_estado'),
        ),
    ]
