# Generated by Django 4.2.13 on 2026-05-30 14:21

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Qué se pidió', max_length=250)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_pedido', models.DateField(default=datetime.date.today)),
                ('fecha_entrega_estimada', models.DateField(help_text='Plazo comprometido por el proveedor')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido a proveedor',
                'verbose_name_plural': 'Pedidos a proveedores',
                'db_table': 'pedidos_proveedor',
                'ordering': ['-fecha_pedido', 'fecha_entrega_estimada'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(blank=True, max_length=30)),
                ('contacto', models.CharField(blank=True, help_text='Persona de contacto', max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('rubro', models.CharField(blank=True, help_text='Qué provee (ej: porcelanatos)', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='cheque_banco',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='cheque_fecha_cobro',
            field=models.DateField(blank=True, help_text='Fecha en que el cheque puede cobrarse (plazo)', null=True),
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='cheque_numero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('cheque', 'Cheque')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='gastooperativo',
            index=models.Index(fields=['cheque_fecha_cobro'], name='idx_gasto_cheque'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='costos.proveedor'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_proveedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gastooperativo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='costos.proveedor'),
        ),
        migrations.AddIndex(
            model_name='pedidoproveedor',
            index=models.Index(fields=['estado', 'fecha_entrega_estimada'], name='idx_pedprov_estado'),
        ),
    ]
