# Generated by Django 4.2.13 on 2026-08-09 17:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_tipos_instalacion_and_more'),
        ('costos', '0003_pedidoproveedor_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='cantidad_pedida',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad pedida, en la unidad de venta del producto', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto del catálogo que se está reponiendo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_proveedor', to='productos.producto'),
        ),
    ]
