# Generated by Django 4.2.13 on 2026-08-11 22:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costos', '0004_pedidoproveedor_cantidad_pedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='unidad_pedido',
            field=models.CharField(choices=[('venta', 'Unidad de venta (m²/unidad)'), ('caja', 'Cajas'), ('pallet', 'Pallets')], default='venta', help_text='Unidad en la que se cargó cantidad_pedida — a los proveedores se les compra en pallets o cajas, no en m², así que se guarda tal como se pidió en vez de convertir a m² de entrada y perder ese dato.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_pedida',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad pedida, en la unidad indicada por unidad_pedido', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
