# Generated by Django 4.2.13 on 2026-08-23 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caja', '0004_sesioncaja_unique_sesion_abierta_por_cajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdc', models.CharField(db_index=True, help_text='Código de Control de 44 dígitos. Se calcula localmente.', max_length=44, unique=True)),
                ('tipo_documento', models.PositiveSmallIntegerField(default=1)),
                ('establecimiento', models.CharField(max_length=3)),
                ('punto_expedicion', models.CharField(max_length=3)),
                ('numero', models.PositiveIntegerField()),
                ('numero_completo', models.CharField(db_index=True, help_text='EEE-PPP-NNNNNNN', max_length=15)),
                ('codigo_seguridad', models.CharField(max_length=9)),
                ('fecha_emision', models.DateTimeField()),
                ('emisor_ruc', models.CharField(max_length=20)),
                ('emisor_razon_social', models.CharField(max_length=180)),
                ('emisor_direccion', models.CharField(blank=True, max_length=250)),
                ('emisor_telefono', models.CharField(blank=True, max_length=40)),
                ('emisor_timbrado', models.CharField(blank=True, max_length=20)),
                ('emisor_timbrado_vto', models.CharField(blank=True, max_length=20)),
                ('receptor_ruc', models.CharField(blank=True, max_length=20)),
                ('receptor_razon_social', models.CharField(max_length=180)),
                ('receptor_direccion', models.CharField(blank=True, max_length=250)),
                ('receptor_telefono', models.CharField(blank=True, max_length=40)),
                ('receptor_email', models.EmailField(blank=True, max_length=254)),
                ('receptor_naturaleza', models.PositiveSmallIntegerField(default=2, help_text='1 contribuyente, 2 no contribuyente.')),
                ('condicion_venta', models.PositiveSmallIntegerField(default=1)),
                ('medio_pago', models.PositiveSmallIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_gravado_10', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_gravado_5', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_exento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_10', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_5', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('firmado', 'Firmado'), ('enviado', 'Enviado, esperando respuesta'), ('aprobado', 'Aprobado por el SIFEN'), ('rechazado', 'Rechazado por el SIFEN'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=12)),
                ('xml_generado', models.TextField(blank=True, help_text='XML del DE. Se guarda para poder reenviarlo.')),
                ('xml_firmado', models.TextField(blank=True)),
                ('respuesta_sifen', models.TextField(blank=True, help_text='Última respuesta del SIFEN, tal cual vino.')),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento electrónico',
                'verbose_name_plural': 'Documentos electrónicos',
                'db_table': 'fe_documentos_electronicos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(help_text='Código iTiDE del SIFEN. 1 = factura.')),
                ('establecimiento', models.CharField(max_length=3)),
                ('punto_expedicion', models.CharField(max_length=3)),
                ('ultimo_numero', models.PositiveIntegerField(default=0, help_text='Último número emitido. El próximo comprobante lleva este + 1.')),
                ('numero_desde', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_hasta', models.PositiveIntegerField(default=9999999, validators=[django.core.validators.MinValueValidator(1)])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secuencia de comprobante',
                'verbose_name_plural': 'Secuencias de comprobante',
                'db_table': 'fe_secuencias_comprobante',
            },
        ),
        migrations.AddConstraint(
            model_name='secuenciacomprobante',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'establecimiento', 'punto_expedicion'), name='uq_secuencia_por_punto_expedicion'),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_electronicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='pago',
            field=models.OneToOneField(help_text='El cobro que originó este comprobante.', on_delete=django.db.models.deletion.PROTECT, related_name='documento_electronico', to='caja.pago'),
        ),
        migrations.AddIndex(
            model_name='documentoelectronico',
            index=models.Index(fields=['estado', 'fecha_emision'], name='idx_de_estado_fecha'),
        ),
    ]
