# Generated by Django 4.2.13 on 2026-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoelectronico',
            name='documento_asociado_cdc',
            field=models.CharField(blank=True, db_index=True, help_text='CDC del documento que esta nota corrige. Obligatorio en notas de crédito y débito.', max_length=44),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='motivo_nota',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Código iMotEmi del motivo de la nota (1 devolución y ajuste, 2 devolución, 3 descuento...). Ver codigos.MOTIVOS_NOTA.', null=True),
        ),
    ]
