# Generated by Django 4.2.13 on 2026-09-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_datostarjeta'),
        ('facturacion', '0002_documentoelectronico_documento_asociado_cdc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoelectronico',
            name='pago',
            field=models.ForeignKey(help_text='El cobro que originó este comprobante.', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_electronicos', to='caja.pago'),
        ),
        migrations.AddConstraint(
            model_name='documentoelectronico',
            constraint=models.UniqueConstraint(fields=('pago', 'tipo_documento'), name='uq_un_documento_por_tipo_y_cobro'),
        ),
    ]
