# Generated by Django 4.2.13 on 2026-09-14 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_identidad_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0003_alter_documentoelectronico_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.PositiveSmallIntegerField(default=1, help_text='Código E501: 1 traslado por venta, 6 por devolución, 7 entre locales... Ver codigos.MOTIVOS_TRASLADO.')),
                ('responsable', models.PositiveSmallIntegerField(default=1, help_text='Código E503: quién emite la nota. 1 = el emisor de la factura, que es el caso del negocio.')),
                ('fecha_inicio_traslado', models.DateField(help_text='Cuándo sale la mercadería del local.')),
                ('fecha_fin_traslado', models.DateField(blank=True, help_text='Cuándo se estima que llega.', null=True)),
                ('kilometros', models.PositiveIntegerField(blank=True, help_text='Distancia estimada del recorrido.', null=True)),
                ('tipo_transporte', models.PositiveSmallIntegerField(default=1, help_text='Código E901: 1 propio, 2 de terceros.')),
                ('modalidad', models.PositiveSmallIntegerField(default=1, help_text='Código E903: 1 terrestre, 2 fluvial, 3 aéreo, 4 multimodal.')),
                ('responsable_flete', models.PositiveSmallIntegerField(default=5, help_text='Código E905. 5 = transporte propio, que es el caso cuando entrega el camión del negocio.')),
                ('vehiculo_tipo', models.CharField(blank=True, help_text='Camión, camioneta... Tiene que ser coherente con la modalidad (E961).', max_length=10)),
                ('vehiculo_marca', models.CharField(blank=True, max_length=10)),
                ('vehiculo_matricula', models.CharField(blank=True, help_text='La chapa. Es la identificación habitual de un camión local (E965).', max_length=6)),
                ('vehiculo_numero', models.CharField(blank=True, help_text='Número de identificación, si no se usa la matrícula (E963).', max_length=20)),
                ('transportista_nombre', models.CharField(blank=True, max_length=60)),
                ('transportista_ruc', models.CharField(blank=True, max_length=20)),
                ('transportista_documento', models.CharField(blank=True, help_text='Cédula, cuando el transportista no es contribuyente.', max_length=20)),
                ('conductor_nombre', models.CharField(blank=True, max_length=60)),
                ('conductor_documento', models.CharField(blank=True, max_length=20)),
                ('direccion_salida', models.CharField(blank=True, max_length=255)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('entrega_numero_casa', models.CharField(blank=True, default='0', max_length=20)),
                ('entrega_departamento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entrega_departamento_desc', models.CharField(blank=True, max_length=40)),
                ('entrega_distrito', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('entrega_distrito_desc', models.CharField(blank=True, max_length=40)),
                ('entrega_ciudad', models.PositiveIntegerField(blank=True, null=True)),
                ('entrega_ciudad_desc', models.CharField(blank=True, max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_registrados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(help_text='El pedido cuya mercadería se traslada.', on_delete=django.db.models.deletion.PROTECT, related_name='datos_traslado', to='ventas.notapedido')),
            ],
            options={
                'verbose_name': 'Datos de traslado',
                'verbose_name_plural': 'Datos de traslado',
                'db_table': 'fe_datos_traslado',
            },
        ),
    ]
