# Generated by Django 4.2.13 on 2026-09-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_datostraslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostraslado',
            name='kilometros',
            field=models.PositiveIntegerField(blank=True, help_text='Kilómetros estimados de recorrido (E505). La NT 010 lo volvió OBLIGATORIO para la nota de remisión, así que sin esto el documento vuelve rechazado. Queda nullable en la base para no romper filas viejas; clean() lo exige.', null=True),
        ),
        migrations.AlterField(
            model_name='datostraslado',
            name='vehiculo_matricula',
            field=models.CharField(blank=True, help_text='La chapa. Es la identificación habitual de un camión local (E965). La NT 005 amplió el campo de 6 a 7.', max_length=7),
        ),
    ]
