# Generated by Django 4.2.13 on 2026-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_datostraslado_kilometros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datostraslado',
            name='conductor_direccion',
            field=models.CharField(blank=True, help_text='Obligatoria cuando se declara un chofer.', max_length=255),
        ),
        migrations.AddField(
            model_name='datostraslado',
            name='salida_ciudad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datostraslado',
            name='salida_ciudad_desc',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='datostraslado',
            name='salida_numero_casa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='datostraslado',
            name='transportista_direccion',
            field=models.CharField(blank=True, help_text='Obligatoria cuando se declara un transportista (E10.4).', max_length=255),
        ),
    ]
