# Generated by Django 4.2.13 on 2026-09-20 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0006_datostraslado_conductor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoelectronico',
            name='enlace_qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cancelacion', 'Cancelación de un documento'), ('inutilizacion', 'Inutilización de un rango de números')], db_index=True, max_length=15)),
                ('timbrado', models.CharField(blank=True, max_length=8)),
                ('establecimiento', models.CharField(blank=True, max_length=3)),
                ('punto_expedicion', models.CharField(blank=True, max_length=3)),
                ('numero_desde', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_documento', models.PositiveSmallIntegerField(blank=True, help_text='Código iTiDE del talonario inutilizado. 1 = factura.', null=True)),
                ('motivo', models.CharField(help_text='Texto libre de 5 a 500 caracteres. Lo lee la DNIT.', max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviado', 'Enviado, esperando respuesta'), ('aprobado', 'Aprobado por el SIFEN'), ('rechazado', 'Rechazado por el SIFEN')], db_index=True, default='pendiente', max_length=12)),
                ('xml_enviado', models.TextField(blank=True)),
                ('respuesta_sifen', models.TextField(blank=True)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_fiscales', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, help_text='El DTE que se cancela. Solo en eventos de cancelación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='facturacion.documentoelectronico')),
            ],
            options={
                'verbose_name': 'Evento fiscal',
                'verbose_name_plural': 'Eventos fiscales',
                'db_table': 'fe_eventos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='idx_evento_estado_fecha')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventodocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'cancelacion'), models.Q(('estado', 'rechazado'), _negated=True)), fields=('documento',), name='uq_una_cancelacion_viva_por_documento'),
        ),
    ]
