# Generated by Django 4.2.13 on 2026-09-20 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0007_eventos_y_kude'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, help_text='Número de lote que devolvió el SIFEN (dProtConsLote).', max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado, esperando resultado'), ('procesado', 'Procesado'), ('rechazado', 'Rechazado')], db_index=True, default='enviado', max_length=15)),
                ('cantidad', models.PositiveSmallIntegerField(default=0, help_text='Cuántos documentos se mandaron en este lote.')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('consultas', models.PositiveSmallIntegerField(default=0)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10)),
                ('respuesta_sifen', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_sifen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lote de transmisión',
                'verbose_name_plural': 'lotes de transmisión',
                'db_table': 'sifen_lotes',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='documentoelectronico',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote asincrónico por el que se envió, si no fue sincrónico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='facturacion.lotetransmision'),
        ),
    ]
