# Generated by Django 4.2.13 on 2026-09-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0008_lotetransmision_documentoelectronico_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conformidad', 'Conformidad con el DTE'), ('disconformidad', 'Disconformidad con el DTE'), ('desconocimiento', 'Desconocimiento del DE o DTE'), ('notificacion', 'Notificación de recepción')], db_index=True, max_length=20)),
                ('cdc', models.CharField(db_index=True, help_text='CDC del DTE emitido por el proveedor, 44 dígitos.', max_length=44)),
                ('tipo_conformidad', models.PositiveSmallIntegerField(blank=True, help_text='1 = total, 2 = parcial. Solo en conformidad.', null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, help_text='Fecha estimada de recepción. Obligatoria si la conformidad es parcial, y en desconocimiento y notificación.', null=True)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_emision_documento', models.DateTimeField(blank=True, null=True)),
                ('total_documento', models.DecimalField(blank=True, decimal_places=2, help_text='Total en guaraníes del documento. Lo pide la notificación.', max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviado', 'Enviado, esperando respuesta'), ('aprobado', 'Aprobado por el SIFEN'), ('rechazado', 'Rechazado por el SIFEN')], db_index=True, default='pendiente', max_length=15)),
                ('intentos_envio', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10)),
                ('respuesta_sifen', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_receptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento del receptor',
                'verbose_name_plural': 'eventos del receptor',
                'db_table': 'fe_eventos_receptor',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventoreceptor',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'rechazado'), _negated=True), fields=('cdc', 'tipo'), name='uq_un_evento_receptor_vivo_por_cdc_y_tipo'),
        ),
    ]
