# Generated by Django 4.2.13 on 2026-09-20 16:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_pago_cliente_email'),
        ('facturacion', '0009_eventoreceptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoelectronico',
            name='pago',
            field=models.ForeignKey(blank=True, help_text='El cobro que originó este comprobante. Vacío en la autofactura, que no viene de una venta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_electronicos', to='caja.pago'),
        ),
        migrations.CreateModel(
            name='ItemAutofactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tasa_iva', models.PositiveSmallIntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_autofactura', to='facturacion.documentoelectronico')),
            ],
            options={
                'db_table': 'fe_items_autofactura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DatosAutofactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturaleza_vendedor', models.PositiveSmallIntegerField(choices=[(1, 'No contribuyente'), (2, 'Extranjero')], default=1)),
                ('tipo_documento_vendedor', models.PositiveSmallIntegerField(default=1)),
                ('numero_documento_vendedor', models.CharField(max_length=20)),
                ('nombre_vendedor', models.CharField(max_length=60)),
                ('direccion_vendedor', models.CharField(max_length=255)),
                ('numero_casa_vendedor', models.CharField(blank=True, default='0', max_length=10)),
                ('departamento_vendedor', models.PositiveSmallIntegerField()),
                ('departamento_vendedor_desc', models.CharField(max_length=40)),
                ('distrito_vendedor', models.PositiveIntegerField()),
                ('distrito_vendedor_desc', models.CharField(max_length=40)),
                ('ciudad_vendedor', models.PositiveIntegerField()),
                ('ciudad_vendedor_desc', models.CharField(max_length=40)),
                ('lugar_transaccion', models.CharField(max_length=255)),
                ('departamento_transaccion', models.PositiveSmallIntegerField()),
                ('departamento_transaccion_desc', models.CharField(max_length=40)),
                ('distrito_transaccion', models.PositiveIntegerField()),
                ('distrito_transaccion_desc', models.CharField(max_length=40)),
                ('ciudad_transaccion', models.PositiveIntegerField()),
                ('ciudad_transaccion_desc', models.CharField(max_length=40)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_autofactura', to='facturacion.documentoelectronico')),
            ],
            options={
                'verbose_name': 'datos de autofactura',
                'verbose_name_plural': 'datos de autofactura',
                'db_table': 'fe_datos_autofactura',
            },
        ),
    ]
