# Generated by Django 4.2.13 on 2026-05-26 21:31

import apps.productos.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Acabado',
                'verbose_name_plural': 'Acabados',
                'db_table': 'acabados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('piso', 'Pisos'), ('porcelanato', 'Porcelanatos'), ('ceramica', 'Cerámicas'), ('sanitario', 'Sanitarios'), ('accesorio_bano', 'Accesorios de Baño'), ('cocina', 'Artículos de Cocina'), ('otro', 'Otro')], db_index=True, default='otro', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=60)),
                ('activa', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=240, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio de venta base en Gs. (puede diferir por variante)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de costo — solo visible para administradores', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_venta', models.CharField(choices=[('m2', 'Metro cuadrado'), ('pieza', 'Pieza'), ('juego', 'Juego'), ('caja', 'Caja'), ('ml', 'Metro lineal')], default='m2', max_length=10)),
                ('destacado', models.BooleanField(db_index=True, default=False, help_text='Aparece primero en el showroom y catálogo')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('visible_showroom', models.BooleanField(default=True, help_text='Visible para vendedores en el showroom de tablets')),
                ('notas_internas', models.TextField(blank=True, help_text='Solo visible para el personal, no aparece en el showroom')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-destacado', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de instalación',
                'verbose_name_plural': 'Tipos de instalación',
                'db_table': 'tipos_instalacion',
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, help_text='Ej: Beige, Gris Cemento, Blanco Nieve', max_length=80)),
                ('largo_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Largo de la pieza en centímetros', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Ancho de la pieza en centímetros', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('espesor_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Espesor en milímetros', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('piezas_por_caja', models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de piezas por caja o paquete', null=True)),
                ('m2_por_caja', models.DecimalField(blank=True, decimal_places=4, help_text='M² que cubre una caja completa (se calcula si se dejan las dimensiones)', max_digits=7, null=True)),
                ('peso_kg_caja', models.DecimalField(blank=True, decimal_places=2, help_text='Peso de la caja en kg', max_digits=6, null=True)),
                ('precio_diferencial', models.DecimalField(blank=True, decimal_places=2, help_text='Precio propio de esta variante. Si es nulo, hereda el precio base del producto.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('acabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.acabado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'db_table': 'variantes',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipos_instalacion',
            field=models.ManyToManyField(blank=True, to='productos.tipoinstalacion'),
        ),
        migrations.CreateModel(
            name='ImagenVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen que muestra el color/acabado real de esta variante', upload_to=apps.productos.models.variante_imagen_path)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.variante')),
            ],
            options={
                'verbose_name': 'Imagen de variante',
                'verbose_name_plural': 'Imágenes de variante',
                'db_table': 'imagenes_variante',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Formatos: JPG, PNG, WEBP. Máximo 5 MB. Recomendado: 1200×1200 px.', upload_to=apps.productos.models.producto_imagen_path)),
                ('es_principal', models.BooleanField(default=False, help_text='Esta imagen se muestra en el showroom y listados')),
                ('titulo', models.CharField(blank=True, help_text='Descripción breve de la imagen (texto alternativo)', max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden en la galería del producto (menor número = primero)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'db_table': 'imagenes_producto',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['tipo', 'activa'], name='idx_categoria_tipo_activa'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['producto', 'activa'], name='idx_variante_producto'),
        ),
        migrations.AlterUniqueTogether(
            name='variante',
            unique_together={('producto', 'color', 'acabado', 'largo_cm', 'ancho_cm')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'visible_showroom'], name='idx_producto_showroom'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='idx_producto_categoria'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca', 'activo'], name='idx_producto_marca'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-destacado', 'nombre'], name='idx_producto_orden'),
        ),
        migrations.AddIndex(
            model_name='imagenvariante',
            index=models.Index(fields=['variante', 'es_principal'], name='idx_img_var_principal'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', 'es_principal'], name='idx_img_prod_principal'),
        ),
    ]
