# Generated by Django 4.2.13 on 2026-06-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='calidad',
            field=models.CharField(blank=True, help_text='Calidad/clase comercial. Ej: TP.A, Primera, Comercial', max_length=20),
        ),
    ]
