# Generated by Django 4.2.13 on 2026-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_variante_calidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipos_instalacion',
        ),
        migrations.AddField(
            model_name='variante',
            name='cajas_por_pallet',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de cajas por pallet (para cargar stock en pallets)', null=True),
        ),
        migrations.AddField(
            model_name='variante',
            name='montaje_grifo',
            field=models.CharField(blank=True, choices=[('mesa', 'De mesa'), ('pared', 'De pared')], max_length=20),
        ),
        migrations.AddField(
            model_name='variante',
            name='posicion_grifo',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('baja', 'Baja')], max_length=20),
        ),
        migrations.AddField(
            model_name='variante',
            name='tipo_cisterna',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('baja', 'Baja')], max_length=20),
        ),
        migrations.AddField(
            model_name='variante',
            name='tipo_ducha',
            field=models.CharField(blank=True, choices=[('frio', 'Frío'), ('electrico', 'Eléctrico'), ('monocomando', 'Monocomando')], max_length=20),
        ),
        migrations.AddField(
            model_name='variante',
            name='tipo_grifo',
            field=models.CharField(blank=True, choices=[('frio', 'Frío'), ('monocomando', 'Monocomando')], max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('piso', 'Pisos'), ('porcelanato', 'Porcelanatos'), ('ceramica', 'Cerámicas'), ('sanitario', 'Sanitarios'), ('accesorio_bano', 'Accesorios de Baño'), ('cocina', 'Artículos de Cocina'), ('bacha', 'Bachas'), ('pileta_cocina', 'Piletas para cocina'), ('pileta_ropa', 'Piletas para ropa'), ('griferia', 'Grifería'), ('ducha', 'Duchas'), ('inodoro', 'Inodoros'), ('migitorio', 'Migitorios'), ('bide', 'Bidés'), ('ducha_higienica', 'Duchas higiénicas'), ('cisterna', 'Cisternas'), ('tapa_inodoro', 'Tapas para inodoro'), ('nicho_bano', 'Nichos para baño'), ('espejo', 'Espejos'), ('adhesivo', 'Adhesivos'), ('pastina', 'Pastinas'), ('plomeria', 'Plomería'), ('tira_fondo', 'Tiras de fondo con tarugo'), ('otro', 'Otro')], db_index=True, default='otro', max_length=30),
        ),
        migrations.DeleteModel(
            name='TipoInstalacion',
        ),
    ]
