# Generated by Django 4.2.13 on 2026-08-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_tipos_instalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tasa_iva',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Gravado 10%'), (5, 'Gravado 5%'), (0, 'Exento')], default=10, help_text='Tasa de IVA incluida en el precio. El rubro (pisos, cerámicos, sanitarios) va al 10%.'),
        ),
    ]
