# Generated by Django 4.2.13 on 2026-08-25 18:25

import apps.productos.codigo_barras
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_tasa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EAN-13 de la caja, o el interno que genera el sistema. Se puede cargar escaneándolo con el lector.', max_length=32, validators=[apps.productos.codigo_barras.validar_codigo_barras]),
        ),
        migrations.AddConstraint(
            model_name='variante',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras', ''), _negated=True), fields=('codigo_barras',), name='uniq_variante_codigo_barras'),
        ),
    ]
