# Generated by Django 4.2.13 on 2026-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_tasa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras de la caja. Se completa con el lector.', max_length=64, null=True, unique=True),
        ),
    ]
