# Generated by Django 4.2.13 on 2026-08-24 14:23
#
# Reescrita el 27/08/2026. La versión original era un AddField simple, y no
# se podía aplicar en la base del negocio: la columna YA EXISTÍA ahí, creada
# por la otra implementación del lector de código de barras (la que se
# descartó al unificar, commit 6f99c13), pero con otra forma —
# `varchar(32) NOT NULL` y un índice único parcial `WHERE codigo_barras <> ''`,
# el diseño de "cadena vacía = sin código".
#
# El resultado era un bloqueo total del alta de productos: el modelo guarda
# NULL cuando no hay código, la columna no lo aceptaba, y cualquier intento de
# crear una Variante moría con
#     IntegrityError: null value in column "codigo_barras" ... not-null
# tanto desde la pantalla de Productos como desde los comandos de carga.
# `migrate` tampoco resolvía nada: el AddField original chocaba contra la
# columna existente.
#
# Esta versión deja la columna igual a lo que declara el modelo
# (`varchar(64) NULL UNIQUE`, ver apps/productos/models.py) en los dos casos:
# base nueva (setup.bat en una PC limpia) y base del negocio ya en uso. Es
# idempotente: correrla dos veces no rompe nada.
#
# No hay pérdida de datos: ninguna variante tenía un código cargado.
from django.db import migrations, models

CAMPO = models.CharField(
    blank=True, db_index=True, max_length=64, null=True, unique=True,
    help_text='Código de barras de la caja. Se completa con el lector.',
)

# Normaliza una columna preexistente a lo que declara el modelo. Cada
# sentencia es idempotente, así que no importa en qué estado esté.
SQL_RECONCILIAR = """
ALTER TABLE variantes ALTER COLUMN codigo_barras TYPE varchar(64);
ALTER TABLE variantes ALTER COLUMN codigo_barras DROP NOT NULL;
UPDATE variantes SET codigo_barras = NULL WHERE codigo_barras = '';
DROP INDEX IF EXISTS uniq_variante_codigo_barras;
CREATE UNIQUE INDEX IF NOT EXISTS variantes_codigo_barras_key
    ON variantes (codigo_barras);
CREATE INDEX IF NOT EXISTS variantes_codigo_barras_edec9bb9
    ON variantes (codigo_barras);
CREATE INDEX IF NOT EXISTS variantes_codigo_barras_edec9bb9_like
    ON variantes (codigo_barras varchar_pattern_ops);
"""


def _existe_columna(schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return False
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = 'variantes' AND column_name = 'codigo_barras'")
        return cursor.fetchone() is not None


def crear_o_reconciliar(apps, schema_editor):
    """Agrega la columna, o corrige la que ya está."""
    if _existe_columna(schema_editor):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(SQL_RECONCILIAR)
        return

    modelo = apps.get_model('productos', 'Variante')
    campo = CAMPO.clone()
    campo.set_attributes_from_name('codigo_barras')
    schema_editor.add_field(modelo, campo)


def quitar(apps, schema_editor):
    modelo = apps.get_model('productos', 'Variante')
    campo = CAMPO.clone()
    campo.set_attributes_from_name('codigo_barras')
    schema_editor.remove_field(modelo, campo)


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_tasa_iva'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='variante',
                    name='codigo_barras',
                    field=CAMPO,
                ),
            ],
            database_operations=[
                migrations.RunPython(crear_o_reconciliar, quitar),
            ],
        ),
    ]
