# Generated by Django 4.2.13 on 2026-08-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_variante_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras de la caja. Campo en desuso: el sistema de código de barras está desactivado.', max_length=64, null=True, unique=True),
        ),
    ]
