# Generated by Django 4.2.13 on 2026-08-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_variante_codigo_barras'),
        ('productos', '0006_identidad_sync'),
    ]

    operations = [
    ]
