# Generated by Django 4.2.13 on 2026-05-26 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de mercadería'), ('salida', 'Salida por venta'), ('ajuste', 'Ajuste de inventario'), ('reserva', 'Reserva por pedido'), ('liberacion', 'Liberación de reserva'), ('devolucion', 'Devolución')], db_index=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cantidad_anterior', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cantidad_posterior', models.DecimalField(decimal_places=4, max_digits=10)),
                ('referencia_tipo', models.CharField(blank=True, db_index=True, help_text='venta | pedido | ajuste | devolucion', max_length=30)),
                ('referencia_id', models.PositiveBigIntegerField(blank=True, help_text='ID del documento origen (NotaPedido.id, Pago.id, etc.)', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'db_table': 'movimientos_stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, help_text='Cantidad física real en el depósito', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_reservada', models.DecimalField(decimal_places=4, default=0, help_text='Reservada por notas de pedido pendientes de cobro', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0, help_text='Umbral de alerta de stock bajo. 0 = sin alerta.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Pasillo A — Estante 3, Depósito fondo, Exhibición piso', max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('variante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='productos.variante')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'db_table': 'stock',
            },
        ),
    ]
