# Generated by Django 4.2.13 on 2026-05-26 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.variante'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['variante', '-fecha'], name='idx_mov_variante_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo', '-fecha'], name='idx_mov_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['referencia_tipo', 'referencia_id'], name='idx_mov_referencia'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['usuario', '-fecha'], name='idx_mov_usuario_fecha'),
        ),
    ]
