# Generated by Django 4.2.13 on 2026-08-09 16:12

import django.core.validators
from django.db import migrations, models


def backfill_stock_referencia(apps, schema_editor):
    """
    Para las variantes existentes no hay forma de saber cuál fue su stock
    inicial real; se usa la cantidad actual como mejor aproximación del
    100% de referencia (se puede corregir a mano después si hace falta).
    """
    Stock = apps.get_model('inventario', 'Stock')
    Stock.objects.filter(stock_referencia__isnull=True).update(stock_referencia=models.F('cantidad'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock inicial cargado, usado como el 100% de referencia para las alertas de stock bajo (25%) y crítico (15%). Se fija al crear la variante y no se recalcula solo con reposiciones.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(backfill_stock_referencia, noop),
    ]
